import requests
from langchain_community.document_loaders import UnstructuredHTMLLoader
from typing import Optional, List
from langchain_core.pydantic_v1 import BaseModel, Field
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_experimental.llms.ollama_functions import OllamaFunctions
import os
import json
from langchain_openai import ChatOpenAI
from tool import create_example_messages
from utility import extract_secret


class CvInformation(BaseModel):
    """Information about a your resume generated by LLM."""

    position_name: Optional[str] = Field(
        default=None, description="The name of the position."
    )
    company_name: Optional[str] = Field(
        default=None, description="The name of the company offering the job."
    )
    position_level: Optional[str] = Field(
        default=None, description="The level or seniority of the position."
    )
    specializations: Optional[List[str]] = Field(
        default=None, description="The specializations required for the position."
    )
    skills: Optional[List[str]] = Field(
        default=None, description="The skills required for the position."
    )
    about_position: Optional[str] = Field(
        default=None, description="A brief description about the position."
    )
    responsibilities: Optional[List[str]] = Field(
        default=None, description="The responsibilities associated with the position."
    )
    requirements: Optional[List[str]] = Field(
        default=None, description="The requirements needed to qualify for the position."
    )
    about_company: Optional[str] = Field(
        default=None,
        description="A brief description about the company offering the job.",
    )




class ExtractingAgent:
    def __init__(
        self, model: str = "gpt-3.5-turbo", temperature: float = 0, api_key=""
    ):
        self.prompt = ChatPromptTemplate.from_messages(
            [
                (
                    "system",
                    """
                You are an expert extraction algorithm.
                Extract only relevant details from the text:
                - position_name: The name of the position.
                - company_name: The name of the company offering the job.
                - position_level: The level or seniority of the position.
                - specializations: The specializations required for the position.
                - skills: The skills required for the position.
                - about_position: A brief description about the position.
                - responsibilities: The responsibilities associated with the position.
                - requirements: The requirements needed to qualify for the position.
                - about_company: A brief description about the company offering the job.
                If there are additional details do not include them.
                Translate value of attribute always to English.
                If you do not know the value of an attribute asked to extract,
                return null for the attribute's value.
                """,
                ),
                MessagesPlaceholder("examples"),
                ("human", "{text}"),
            ]
        )
        #         self.llm = OllamaFunctions(
        #             model="phi3:medium",
        #             format="json",
        #             temperature=temperature,
        #             keep_alive=0,
        #         )
        self.llm = ChatOpenAI(
            model=model,
            temperature=temperature,
            api_key=api_key,
        )
        self.runnable = self.prompt | self.llm.with_structured_output(schema=JobOffer)
        self.path = ""
        self.path_job_information = ""

    def extract_job_offer(self, html_data: str, messages):
        print("[INFO] Extracting Agent working")
        response = self.runnable.invoke({"text": html_data, "examples": messages})
        print("[INFO] Extracting Agent done working")
        return response

    def create_directories(self, response: JobOffer):
        if not os.path.exists("./data"):
            os.mkdir("./data")

        position_name = response.position_name.replace("/", "_")
        company_name = response.company_name.replace("/", "_")

        path = f"./data/{company_name}/{position_name}/"
        os.makedirs(path, exist_ok=True)
        print(f"[INFO] Created directory {path}")

        return path

    def save_job_listing(self, html_data: str, path: str):
        path = os.path.join(path, "job_listing.txt")
        with open(path, "w") as file:
            file.write(html_data)
        print(f"[INFO] Saved {path}")

    def save_job_information(self, response: JobOffer, url: str, path: str):
        response_data = response.dict()
        response_data["url"] = url

        json_path = os.path.join(path, "job_information.json")
        with open(json_path, "w") as json_file:
            json.dump(response_data, json_file, indent=4)
        print(f"[INFO] Saved {json_path}")

    def url_data(self, url: str, html_path: str = "./job_listing.html") -> str:
        print(f"[INFO] Request")
        response = requests.get(url)
        print(f"[INFO] Response")
        html_content = response.text
        with open(html_path, "w", encoding="utf-8") as file:
            file.write(html_content)
        print(f"[INFO] HTML SAVED")
        loader = UnstructuredHTMLLoader(html_path)
        html_data = loader.load()
        html_data = html_data[0].page_content
        html_data = html_data.replace("\n", " ")
        return html_data

    def process_job_offer(self, url: str):
        html_data = self.url_data(url)
        messages = create_example_messages(examples)
        response = self.extract_job_offer(html_data, messages)
        self.path = self.create_directories(response)
        self.save_job_listing(html_data, self.path )
        self.save_job_information(response, url, self.path )
        self.path_job_information = os.path.join(self.path , 'job_information.json')
        print(f"JSON data saved to {self.path_job_information}")


if __name__ == "__main__":
    extractor = ExtractingAgent(api_key=extract_secret("OPENAI_API_KEY"))
    url = "https://www.pracuj.pl/praca/ai-ml-engineer-warszawa,oferta,1003363060?s=4921b6b8&searchId=MTcxODgyNjgwMTcwOC4zOTk3"
    extractor.process_job_offer(url)
